spring.application.name=TodoApplication

logging.level.org.springframework=info
#spring.security.user.name = 
#spring.security.user.password = dummy
spring.jpa.defer-ddl=true

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb


#spring.datasource.url=jdbc:mysql://localhost:3306/todos?createDatabaseIfNotExist=true
#spring.datasource.username=todos-user
#spring.datasource.password=dummytodos
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# NO dialect property needed


#comment-h2
#spring.datasource.url=jdbc:h2:mem:testdb

#spring.datasource.url=jdbc:mysql://localhost:3306/todos
#spring.datasource.username=todos-user
#spring.datasource.password=dummytodos
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.defer-ddl=true
#spring.jpa.hibernate.ddl-auto=update

# Allow React frontend



# MySQL Configuration ONLY
spring.datasource.url=jdbc:mysql://localhost:3306/todos?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=todos-user
spring.datasource.password=dummytodos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update



spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Remove ALL H2 properties
